config/routes.rb
Rails.application.routes.draw do
  get 'conservation_groups/show'
  get 'users/show'
  get 'chats/index'
  get 'chats/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords'
  }  
  devise_scope :user do
    get 'user/addresses', to: 'users/registrations#new_address'
    post 'user/addresses', to: 'users/registrations#create_address'
  end
  devise_for :conservation_group, controllers: {
    registrations: 'conservation_groups/registrations',
    sessions:      'conservation_groups/sessions',
    passwords:     'conservation_groups/passwords'
  }
  devise_scope :conservation_group do
    get 'conservation_group/addresses', to: 'conservation_groups/registrations#new_address'
    post 'conservation_group/addresses', to: 'conservation_groups/registrations#create_address'
  end
  root to: 'animals#index'
  resources :animals, except: :destroy do
    collection do
      get 'search'
      get 'complex_search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'


  resources :rooms, only: [:index, :create, :show, :destroy] do
    resources :chats, only: [:index, :create]
  end

  resources :users, only: [:index, :show]
  resources :conservation_groups, only: [:index, :show]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_address
  has_many :likes
  has_many :rooms
  has_many :chats,dependent: :destroy

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'

  with_options presence: true do
    validates :nickname
    validates :email, uniqueness: { case_sensitive: true }
  end

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/, message: 'Full-width characters' } do
    validates :last_name, :first_name
  end

  with_options presence: true, format: { with: /[\p{katakana} ー－&&[^ -~｡-ﾟ]]+/, message: 'Full-width katakana characters' } do
    validates :last_name_kana, :first_name_kana
  end

  def liked_by?(animal_id)
    likes.where(animal_id: animal_id).exists?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
     unless @user.valid?
       render :new and return
     end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @user_address = @user.build_user_address
    render :new_user_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @user_address = UserAddress.new(user_address_params)
     unless @user_address.valid?
       render :new_user_address and return
     end
    @user.build_user_address(@user_address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path
  end
 
  private
 
  def user_address_params
    params.require(:user_address).permit(:postal_code, :prefecture_id, :city, :address, :building, :phone_number)
  end
  
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    likes = @user.likes
    @animals = []
    likes.each do |like|
      animal = Animal.find(like.animal_id)
      @animals << animal
    end
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_right_bar.html.erb
<ul class="right-bar" >
  <div class="user-topic">ユーザー情報</div>
  <li class="detail-info">
    <h4 class="detail-heading">ニックネーム</h4>
    <div class="detail-nickname">
      <%= @user.nickname %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">姓</h4>
    <div class="detail-last-name">
      <%= @user.last_name %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">名</h4>
    <div class="detail-first-name">
      <%= @user.first_name %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">姓(カナ)</h4>
    <div class="detail-last-name-kana">
      <%= @user.last_name_kana %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">名(カナ)</h4>
    <div class="detail-first-name-kana">
      <%= @user.first_name_kana %>
    </div>
  </li>
  <div class="user-address-topic">住所情報</div>
  <li class="detail-info">
    <h4 class="detail-heading">郵便番号</h4>
    <div class="detail-postal-code">
      〒<%= @user.user_address.postal_code %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">都道府県</h4>
    <div class="detail-prefecture">
      <%= @user.user_address.prefecture.name %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">市区町村</h4>
    <div class="detail-municipality">
      <%= @user.user_address.city %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">番地</h4>
    <div class="detail-address">
      <%= @user.user_address.address %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">建物名</h4>
    <div class="detail-building">
      <%= @user.user_address.building %>
    </div>
  </li>
  <li class="detail-info">
    <h4 class="detail-heading">電話番号</h4>
    <div class="detail-phone-number">
      <%= @user.user_address.phone_number %>
    </div>
  </li>
</ul>

app/views/users/index.html.erb
<%= render "shared/header" %>

<div class="my_page">
  <div class="center-info">
    <%= render partial: "animals/animal", collection: @animals %>
  </div>
  <%= render partial: "right_bar" %>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="my_page">
  <ul class="user_info">
    <li class="users-likes-index">
      <%= link_to users_path(id: @user.id), class: "likes-link" do %>
        <div class="likes-image">
          <%= image_tag("index-dog-cat.jpeg") %>
        </div>
        <div class="likes-index">
          <span>いいねした投稿一覧</span>
        </div>
      <% end %>
    </li>
    <li class="users-chat-rooms-index" >
      <%= link_to rooms_path(id: current_user.id), class: "rooms-link" do %>
        <div class="chat-image">
          <%= image_tag("chat-dog-cat.png") %>
        </div>
        <div class="chat-index">
          <span>チャットルーム一覧</span>
        </div>
      <% end %>
    </li>
  </ul>
  <%= render partial: "right_bar" %>
</div>