config/routes.rb
Rails.application.routes.draw do
  get 'conservation_groups/show'
  get 'users/show'
  get 'chats/index'
  get 'chats/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords'
  }  
  devise_scope :user do
    get 'user/addresses', to: 'users/registrations#new_address'
    post 'user/addresses', to: 'users/registrations#create_address'
  end
  devise_for :conservation_group, controllers: {
    registrations: 'conservation_groups/registrations',
    sessions:      'conservation_groups/sessions',
    passwords:     'conservation_groups/passwords'
  }
  devise_scope :conservation_group do
    get 'conservation_group/addresses', to: 'conservation_groups/registrations#new_address'
    post 'conservation_group/addresses', to: 'conservation_groups/registrations#create_address'
  end
  root to: 'animals#index'
  resources :animals, except: :destroy do
    collection do
      get 'search'
      get 'complex_search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'


  resources :rooms, only: [:index, :create, :show, :destroy] do
    resources :chats, only: [:index, :create]
  end

  resources :users, only: [:index, :show]
  resources :conservation_groups, only: [:index, :show]

end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user,                 optional: true
  belongs_to :conservation_group,   optional: true
  
  validates :content,               presence: true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
    @chat = Chat.new
    @room = Room.find(params[:room_id])
    @chats = @room.chats.includes(:user, :conservation_group)
  end

  def create
    @room = Room.find(params[:room_id])
      if user_signed_in?
        @chat = @room.chats.new(user_chat_params)
      else
        @chat = @room.chats.new(group_chat_params)
      end
      if @chat.save
        ActionCable.server.broadcast 'chat_channel', content: @chat
      else
        @chats = @room.chats.includes(:user, :conservation_group)
        render :index
      end
  end

  private

  def user_chat_params
    params.require(:chat).permit(:content).merge(user_id: current_user.id, conservation_group_id: nil)
  end

  def group_chat_params
    params.require(:chat).permit(:content).merge(user_id: nil, conservation_group_id: current_conservation_group.id)
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<div class="chat-room">
  <div class="chat-box">
    <div class="chat-face">
      <img src="[自分の画像URL]" alt="自分のチャット画像です。" width="90" height="90">
    </div>
    <div class="chat-area">
      <div class="chat-hukidashi">
        ふきだしなのですーふきだしですーふきだー
      </div>
    </div>
  </div>

  <div class="chat-box">
    <div class="chat-face">
      <img src="[相手の画像URL]" alt="誰かのチャット画像です。" width="90" height="90">
    </div>
    <div class="chat-area">
      <div class="chat-hukidashi someone">
        ふきだしだよ<br>
        へへへ
      </div>
    </div>
  </div>
</div>

app/views/chats/_index.html.erb
<div id="chats">
  <% @room.chats.each do |chat|%>
    <% if user_signed_in? %>
      <% if chat.user_id == current_user.id %>
        <div class="mycomment">
          <p><%= chat.content %></p>
        </div>
      <% else %>
        <div class="fukidasi">
          <div class="chatting">
            <div class="says">
              <p><%= chat.content %></p>
            </div>
          </div>
        </div>
      <%end%>
    <%end %>
    <% if conservation_group_signed_in? %>
      <% if chat.conservation_group_id == current_conservation_group.id %>
        <div class="mycomment">
          <p><%= chat.content %></p>
        </div>
      <%else %>
        <div class="fukidasi">
          <div class="chatting">
            <div class="says">
              <p><%= chat.content %></p>
            </div>
          </div>
        </div>
      <%end%>
    <%end %>
  <%end%>
</div>

app/views/chats/_side_bar.html.erb
<div class = "side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/chats/show.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">

  </div>
</div>