config/routes.rb
Rails.application.routes.draw do
  get 'conservation_groups/show'
  get 'users/show'
  get 'chats/index'
  get 'chats/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords'
  }  
  devise_scope :user do
    get 'user/addresses', to: 'users/registrations#new_address'
    post 'user/addresses', to: 'users/registrations#create_address'
  end
  devise_for :conservation_group, controllers: {
    registrations: 'conservation_groups/registrations',
    sessions:      'conservation_groups/sessions',
    passwords:     'conservation_groups/passwords'
  }
  devise_scope :conservation_group do
    get 'conservation_group/addresses', to: 'conservation_groups/registrations#new_address'
    post 'conservation_group/addresses', to: 'conservation_groups/registrations#create_address'
  end
  root to: 'animals#index'
  resources :animals, except: :destroy do
    collection do
      get 'search'
      get 'complex_search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'


  resources :rooms, only: [:index, :create, :show, :destroy] do
    resources :chats, only: [:index, :create]
  end

  resources :users, only: [:index, :show]
  resources :conservation_groups, only: [:index, :show]

end

app/models/animal.rb
class Animal < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :animal_category
  belongs_to :size
  belongs_to :sex
  belongs_to :prefecture

  has_many :animal_tags
  has_many :tags, through: :animal_tags
  has_many_attached :images
  has_many :likes
  has_many :rooms
  belongs_to :conservation_group

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: :show
  before_action :search_animal, only: [:index, :complex_search]

  def index
    @animals = Animal.includes(:conservation_group, :tags, :likes).with_attached_images.order('created_at DESC')
  end

  def new
    @new_animal = NewAnimal.new
  end

  def create
    @new_animal = NewAnimal.new(new_animal_params)
    tag_list = params[:new_animal][:kind_name]
    if @new_animal.valid?
       @new_animal.save(tag_list)
       redirect_to root_path
    else
       render :new
    end
  end

  def show
  end

  # def search
  #   return nil if params[:keyword] == ""
  #   # tags = []
  #   # params["keyword"].split('、').each do |k|
  #   #   tags.push(Tag.where(['kind_name LIKE ?', "%#{k}%"] ))  
  #   # end
  #   tag = Tag.where(['kind_name LIKE ?', "%#{params[:keyword]}%"] )
  #   render json:{ keyword: tag }
  # end

  def complex_search
    @animals = @q.result.order('created_at DESC')
    render :index
  end

  private

  def new_animal_params
    params.require(:new_animal).permit( :name, :animal_category_id, :size_id, :sex_id, :age, :birth_date, :personality, :prefecture_id, images: [], kind_name: [] ).merge( conservation_group_id: current_conservation_group.id )
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def search_animal
    @q = Animal.ransack(params[:q])
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_animal.html.erb
<div class='animal-content'>
  <%= link_to animal_path(animal.id), class:'animal-list' do %>
    <div class="animal-image">
      <%= image_tag animal.images[0], class: "animal-img" %>
    </div>
    <div class="animal-info">
      <div class="side_by_side">
        <div class="animal-sex-name">
          <% if animal.sex.name == "オス" %>
            <i class="fas fa-paw"></i> : <%= animal.name %>   <i class="fas fa-mars"></i>
          <% else %>
            <i class="fas fa-paw"></i> : <%= animal.name %>   <i class="fas fa-venus"></i>
          <% end %>
        </div>
  <% end %>
        <div id="animal_<%= animal.id %>">
          <%= render partial: 'animals/like', locals: { animal: animal } %>
        </div>
      </div>
    <%= link_to animal_path(animal.id), class:'animal-list' do %>
        <div class="animal-tags-kind-name">
          <i class="fas fa-dog"></i> : <%= animal.tags[0].kind_name %>
        </div> 
        <div class="animal-area" >
          <i class="fas fa-globe-asia"></i> : <%= animal.prefecture.name %>
        </div> 
      </div>
    <%end%>
</div>

app/views/animals/_like.html.erb
  <% if user_signed_in? %>
    <% if current_user.liked_by?(animal.id) %>
      <%= link_to destroy_like_path(animal.id), class: "like-link", method: :DELETE, remote: true do %>
        <i class="fas fa-thumbs-up unlike-btn"></i>
      <% end %>
      <%= animal.likes.count %>
    <% else %>
      <%= link_to create_like_path(animal.id), class: "like-link", method: :POST, remote: true  do %>
        <i class="fas fa-thumbs-up like-btn"></i>
      <% end %>
      <%= animal.likes.count %>
    <% end %>
  <% end %>

app/views/animals/_side_bar.html.erb
<ul class="side_bar">

  <% if !user_signed_in? && !conservation_group_signed_in? %>
    <li class="user_registration">
      <i class="fas fa-user"></i>
      <%= link_to "新規登録", new_user_registration_path %>
    </li>
    <li class="user_session">
      <i class="fas fa-user"></i>
      <%= link_to "ログイン", new_user_session_path %>
    </li>
    <li class="conservation_group_form">
      <i class="fas fa-users"></i>
      <label for="menu_bar01">団体の方はこちら</label>
      <input type="checkbox" id="menu_bar01" />
      <ul id="links01">
        <li class="conservation_group_registration" >
          <i class="fas fa-building"></i>
          <%= link_to "新規登録", new_conservation_group_registration_path %>
        </li>
        <li class="conservation_group_session">
          <i class="fas fa-building"></i>
          <%= link_to "ログイン", new_conservation_group_session_path %>
        </li>
      </ul>
    </li>
  <% elsif user_signed_in? %>
    <li class="login_now">
      <i class="fas fa-sign-out-alt"></i>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </li>
    <li class="my_page_link">
      <i class="fas fa-user"></i>
      <%= link_to "マイページ", user_path(current_user.id) %>
    </li>
  <% elsif conservation_group_signed_in? %>
    <li class="login_now">
      <i class="fas fa-sign-out-alt"></i>
      <%= link_to "ログアウト", destroy_conservation_group_session_path, method: :delete %>
    </li>
    <li class="my_page_link">
      <i class="fas fa-user"></i>
      <%= link_to "マイページ", conservation_group_path(current_conservation_group.id) %>
    </li>
    <li class="animal-post">
    <i class="fas fa-bone"></i>
    <%= link_to "投稿する", new_animal_path %>
    </li>
  <% end %>

  <li class="search-animal">
    <i class="fas fa-search"></i>
    <label for="menu_bar02">探す</label>
    <input type="checkbox" id="menu_bar02" />
    <ul id="links02">
      <%= search_form_for @q, url: complex_search_animals_path do |f| %>
        <li class="search-form-list">
          <%= f.label :kind_name_cont, "犬種・猫種" %>
          <%= f.search_field :tags_kind_name_cont %>
        </li>
        <li class="search-form-list">
          <%= f.label :sex_id_eq, '性別' %>
          <%= f.collection_select :sex_id_eq, Sex.all, :id, :name,  include_blank: '指定なし' %>
        </li>
        <li class="search-form-list">
          <%= f.label :animal_category_id_eq, '種類' %>
          <%= f.collection_select :animal_category_id_eq, AnimalCategory.all, :id, :name,  include_blank: '指定なし' %>
        </li>
        <li class="search-form-list">
          <%= f.label :size_id_eq, '大きさ' %>
          <%= f.collection_select :size_id_eq, Size.all, :id, :name,  include_blank: '指定なし' %>
        </li>
        <li class="search-form-list">
          <%= f.label :prefecture_id_eq, 'エリア' %>
          <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name,  include_blank: '指定なし' %>
        </li>
        <li class="search-form-list">
          <%= f.label :age, '年齢' %>
          <%= f.radio_button :age_lteq, '' %>指定なし
          <%= f.radio_button :age_lteq, '1' %>１歳以下
          <%= f.radio_button :age_lteq, '6' %>6歳以下
          <%= f.radio_button :age_lteq, '10' %>10歳以下
          <%= f.radio_button :age_lteq, '15' %>15歳以下
          <%= f.radio_button :age_gteq, '16' %>16歳以上
        </li>
        <li>
          <%= f.submit '検索' %>
        </li>
      <% end %>
    </ul>
  </li>

</ul>

app/views/animals/complex_search.html.erb
<%= render partial: "animal", collection: @results %>

app/views/animals/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="left-info">
    <%= render partial: "side_bar" %>
  </div>
  <div class="center-info">
    <%= render partial: "animal", collection: @animals %>
  </div>
</div>

app/views/animals/new.html.erb
<div class="new-title">
  <h2>新規投稿</h2>
</div>

<%= form_with model: @new_animal, url: animals_path, local: true do |f| %>
  <%# <%= render "devise/shared/error_messages", resource: @new_animal %> 

  <div class="image-form">
    <div class='form-text-image'>
      <div class="info-image">
        <span class="must">必須</span>画像
      </div>
      <div class="file-field">
        <div class="upload-file">
          <label for="new_animal_image">
            <%= f.file_field :images, name: 'new_animal[images][]', id: 'new_animal_image' , multiple: true %>
          </label>
        </div>
      </div>
    </div>
    <div class="preview-image">
      <div id="image-list"></div>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>名前
    </div>
    <div class="field">
      <%= f.text_field :name, autocomplete: 'off' %>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>カテゴリー
    </div>
    <div class="field">
      <%= f.collection_radio_buttons(:animal_category_id, AnimalCategory.all, :id, :name, {}, {class:"select-box"}) %>
    </div>
  </div>

  <div class='form-text-tag-post'>
    <div class="info">
      <span class="must">必須</span>犬種・猫種
      <%# <span class="must">タグ</span>犬種・猫種 %>
    </div>
    <div class="tag-field">
      <%= f.text_field :kind_name, name: 'new_animal[kind_name][]', autocomplete: 'off' %>
      <%= f.text_field :kind_name, name: 'new_animal[kind_name][]', autocomplete: 'off' %>
      <%= f.text_field :kind_name, name: 'new_animal[kind_name][]', autocomplete: 'off' %>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>大きさ
    </div>
    <div class="field">
      <%= f.collection_radio_buttons(:size_id, Size.all, :id, :name, {}, {class:"select-box"}) %>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>性別
    </div>
    <div class="field">
      <%= f.collection_radio_buttons(:sex_id, Sex.all, :id, :name, {}, {class:"select-box"}) %>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>年齢
    </div>
    <div class="field">
      <%= f.text_field :age, autocomplete: 'off' %>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>誕生日
    </div>
    <div class="field">
      <%= f.date_select :birth_date %>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>性格・特徴
    </div>
    <div class="field">
      <%= f.text_area :personality %>
    </div>
  </div>

  <div class='form-text-post'>
    <div class="info">
      <span class="must">必須</span>エリア
    </div>
    <div class="field">
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"animal-prefecture"}) %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: 'post-actions' %>
  </div>

<% end %>

<div class="visit_root_path">
  <%= link_to "TOPページへ戻る" , root_path %>
</div>

app/views/animals/show.html.erb
<%= render "shared/header" %>

<div class="animal-details">
  <div class="left-bar">
    <div class="detail-animal-name">
      <% if @animal.sex.name == "オス" %>
        <%= @animal.name %><p><small>くん</small></p>
      <% else %>
        <%= @animal.name %><p><small>ちゃん</small></p>
      <% end %>
    </div>
    <div class="detail-images">
      <div class="slider">
        <% @animal.images.each do |image| %>
          <%= image_tag image, class:'animal-images' %>
        <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="form-link">
        <div class="chat-link">
          <%= link_to rooms_path(room: { name: "#{current_user.nickname}と#{@animal.conservation_group.nickname}のトーク", user_id: current_user.id, conservation_group_id: @animal.conservation_group_id, animal_id: @animal.id }), method: :post do %>
            <i class="far fa-comment"></i>
            <span>お問い合わせはこちらから</span>
          <% end %>
        </div>
        <div class="visit-link">
          <%= link_to "#" do %>
            <i class="fas fa-home"></i>
            <span>見学予約はこちらから</span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <ul class="right-bar" >
    <div class="detail-head">詳細情報</div>
    <li class="detail-info">
      <h4 class="detail-heading">名前</h4>
      <div class="detail-name">
        <%= @animal.name %>
      </div>
    </li>
     <li class="detail-info">
      <h4 class="detail-heading">種類</h4>
      <div class="detail-kind-name">
        <% @animal.tags.each do |tag| %>
          <%= tag.kind_name %><br>
        <% end %>
      </div>
    </li>
    <li class="detail-info">
      <h4 class="detail-heading">年齢</h4>
      <div class="detail-age">
        <%= @animal.age %>才
      </div>
    </li>
    <li class="detail-info">
      <h4 class="detail-heading">性格・特徴</h4>
      <div class="detail-personality">
        <%= @animal.personality %>
      </div>
    </li>
    <li class="detail-info">
      <h4 class="detail-heading">大きさ</h4>
      <div class="detail-size">
        <%= @animal.size.name %>
      </div>
    </li>
    <li class="detail-info">
      <h4 class="detail-heading">性別</h4>
      <div class="detail-sex">
        <%= @animal.sex.name %>
      </div>
    </li>
    <li class="detail-info">
      <h4 class="detail-heading">エリア</h4>
      <div class="detail-prefecture">
        <%= @animal.prefecture.name %>
      </div>
    </li>
    <li class="detail-info">
      <h4 class="detail-heading">誕生日</h4>
      <div class="detail-birth-date">
        <%= @animal.birth_date %>
      </div>
    </li>
    <li class="detail-info">
      <h4 class="detail-group-name">団体名</h4>
      <div class="detail-group-name">
        <%= @animal.conservation_group.group_name %>
      </div>
    </li>
  </ul>

</div>