config/routes.rb
Rails.application.routes.draw do
  get 'conservation_groups/show'
  get 'users/show'
  get 'chats/index'
  get 'chats/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords'
  }  
  devise_scope :user do
    get 'user/addresses', to: 'users/registrations#new_address'
    post 'user/addresses', to: 'users/registrations#create_address'
  end
  devise_for :conservation_group, controllers: {
    registrations: 'conservation_groups/registrations',
    sessions:      'conservation_groups/sessions',
    passwords:     'conservation_groups/passwords'
  }
  devise_scope :conservation_group do
    get 'conservation_group/addresses', to: 'conservation_groups/registrations#new_address'
    post 'conservation_group/addresses', to: 'conservation_groups/registrations#create_address'
  end
  root to: 'animals#index'
  resources :animals, except: :destroy do
    collection do
      get 'search'
      get 'complex_search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'


  resources :rooms, only: [:index, :create, :show, :destroy] do
    resources :chats, only: [:index, :create]
  end

  resources :users, only: [:index, :show]
  resources :conservation_groups, only: [:index, :show]

end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  belongs_to :conservation_group
  belongs_to :animal
  has_many :chats,dependent: :destroy

  validates :name, presence: true

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end

  def create
    @room = Room.where(user_id: params[:room][:user_id], conservation_group_id: params[:room][:conservation_group_id], animal_id: params[:room][:animal_id]).first_or_initialize(room_params)
    @room.save
    @chat = Chat.new
  end

  def show
    @room = Room.find(params[:id])
    @user = @room.user
    @rooms = @user.rooms
    @chat = Chat.new
  end

  private

  def room_params
    params.require(:room).permit(:name, :user_id, :conservation_group_id, :animal_id)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_main_chat.html.erb
<div class="main-header">
  <div class="header-title">
    <% if user_signed_in? %>
      <h2 style="text-align:center"><%="#{@room.conservation_group.nickname}さんとのチャット"%></h2>
    <% elsif conservation_group_signed_in? %>
      <h2 style="text-align:center"><%="#{@room.user.nickname}さんとのチャット"%></h2>
    <% end %>
  </div>
</div>

<div class="chat-main">
  <%= render partial: "chats/index" %>
</div>

<div class="footer-form">
  <%= form_with model: [@room, @chat], class: 'chat-form' do |f| %>
    <div class="form-input">
      <%= f.text_field   :content, class: 'form-message', autocomplete: 'off' %>
      <label class="form-image">
        <i class="far fa-image fa-3x"></i>
        <%= f.file_field :image, class: 'hidden' %>
      </label>
    </div>
    <%= f.submit '送信', id: 'btn', class: 'chat-form-submit' %>
  <% end %>
</div>

app/views/rooms/_side_bar.html.erb
<div class="side-bar">
  <div class="side-header">
    <div class="header-name">
      <%= link_to @user.nickname, user_path(@user.id) %>
    </div>
  </div>
  <div class="chat-rooms">
    <% @rooms.each do |room| %>
      <div class="room">
        <div class="room-name">
          <%= link_to room.conservation_group.nickname, room_path(room.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/create.html.erb
こんにちは

app/views/rooms/index.html.erb
<div class='chat-wrapper'>
  <div class='side-bar'>
    <%= render 'side_bar' %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class='chat-wrapper'>
  <div class='side-bar'>
    <%= render 'side_bar' %>
  </div>
  <div class= 'main-chat'>
    <%= render 'main_chat'%>
  </div>
</div>